### 1

In [11]:
import numpy as np
import pandas as pd

In [12]:
a = np.arange(12, 24, 1)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

### 2

In [8]:
arrays = []
sizes = [(2, 6), (3, 4), (4, 3), (6, 2), (12, 1)]
for s in sizes:
    arrays.append(a.reshape(s))
print(*arrays, sep='\n\n')

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


### 3

In [13]:
arrays = []
sizes = [(-1, 6), (-1, 4), (-1, 2), (-1, 2), (-1, 1)]
for s in sizes:
    arrays.append(a.reshape(s))
print(*arrays, sep='\n\n')

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


### 4

### 5

In [25]:
mean = 0.0
std = 1.0

In [26]:
b1 = np.random.normal(mean, std, (3, 4))
b1

array([[-0.80729278,  1.58424608,  1.35973783, -0.10032307],
       [ 2.0298493 , -1.59204035, -1.2194707 , -0.27473547],
       [-0.91932506,  1.49325954,  0.22574711,  1.35389863]])

In [27]:
b1 = b1.flatten()
b1

array([-0.80729278,  1.58424608,  1.35973783, -0.10032307,  2.0298493 ,
       -1.59204035, -1.2194707 , -0.27473547, -0.91932506,  1.49325954,
        0.22574711,  1.35389863])

In [28]:
b1.size

12

### 6

In [29]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### 7

In [32]:
b = np.arange(20, 1, -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### 8

In [36]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [37]:
v.size

10

### 9

In [38]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
A = np.reshape(a, (4, 3))
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [40]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [41]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [42]:
B.shape

(4, 4)

In [43]:
np.linalg.det(B)

0.0

### 10

In [45]:
np.random.seed(42)

In [46]:
rng = np.random.default_rng(seed=42)
rng

Generator(PCG64) at 0x289C1F779E0

### 11

In [47]:
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

### 12

In [48]:
C = c.reshape(4, 4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [49]:
D = B + C * 10
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [50]:
np.linalg.det(D)

-28511999.999999944

In [51]:
np.linalg.matrix_rank(D)

4

In [52]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

### 13

In [53]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [55]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [56]:
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [54]:
E = np.where(D_inv > 0, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])