In [30]:
import numpy as np 

In [31]:
a = np.array([[ 1, 6],
              [ 2, 8],
              [ 3, 11],
              [ 3, 10],
              [ 1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [32]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

In [33]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [34]:
[b, c] = np.hsplit(a_centered, 2)

In [35]:
b = b.flatten()
b

array([-1.,  0.,  1.,  1., -1.])

In [36]:
c = c.flatten()
c

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [37]:
c.shape == b.shape

True

In [38]:
a_centered_sp = np.dot(b, c)
a_centered_sp 

8.0

In [39]:
a_centered_sp = a_centered_sp / (len(a) - 1)
a_centered_sp

2.0